### ISSUE TITLE
IO.js?

### ISSUE THREAD

**Issue by chrisbuttery** [OiNutter/nodenv#10]
I'm just wondering if nodenv is thinking about including an option install [io.js](https://iojs.org/) ?

**Comment by peterkc** [comment]
@chrisbuttery for now, a workaround is to create a definition file.

Create the following file **1.0.3-io**
```
install_package "iojs-v1.0.3-linux-x64" "https://iojs.org/dist/v1.0.3/iojs-v1.0.3-linux-x64.tar.gz#1599fb15b1b9fb3a6a0dba338d29df10249ccb0b" copy
```

Then from a prompt, run:
```
bash$ nodenv install ./1.0.3-io
```

**Comment by chrisbuttery** [comment]
Thanks @peterkc

**Comment by OiNutter** [comment]
In all honesty I've given it absolutely no thought as I've not really been following the io.js stuff. I will try and find time this month to take a look. 

@peterkc is there likely more work required than just creating the definition file to make this compatible?

**Comment by KaoruDev** [comment]
:+1:

**Comment by gauravagarwalr** [comment]
What needs to be done to make this happen? I would love to make this a reality! :)

**Comment by jasonkarns** [comment]
iojs has been added to node-build

iojs scraper added: https://github.com/OiNutter/node-build/commit/3e85330675899c81394a3e67101e0dbd35af84b6

iojs-0.12.0-dev: https://github.com/OiNutter/node-build/commit/d30c639dfd3a5470b4be4f711a4526a3c0df9598
iojs builds 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4: https://github.com/OiNutter/node-build/commit/3a55dd9fd9dcd86608f74912d8b118aa044c60b0
iojs build 1.1.0: https://github.com/OiNutter/node-build/commit/97d0b526a2a8118a124f8cb918145684a8ff2017
iojs build 1.2.0: https://github.com/OiNutter/node-build/commit/b00cb0b93cab09b117fe76600c56d7b6904aaf4b
iojs build 1.3.0: https://github.com/OiNutter/node-build/commit/3bac9dc85aee50692536b2ac00704a994e44a33d

iojs build 1.4.1, 1.4.2, 1.4.3: https://github.com/OiNutter/node-build/commit/ba04ae4d349714e359cb720dd6e66d36fb2f6f3c
iojs build 1.5.0, 1.5.1: https://github.com/OiNutter/node-build/commit/67e0cfb4cb8a5fae6897531b9f714bfadd9ec2bd
iojs build 1.6.0, 1.6.1, 1.6.2: https://github.com/OiNutter/node-build/commit/c4a0b7818062313df585211d72490097fe7a5c8a
iojs build for 1.x devline branch: https://github.com/OiNutter/node-build/commit/4e2e08f28e39ef3c5c4428680d336fcf346263d7

**Comment by peterkc** [comment]
@jasonkarns after looking at the request to get definition files for binary builds. I'm wondering if it would be better to have a "node-definition" plugin that is response for helping create definition files. This would avoid having to scrape nodejs.org and iojs.org for new releases.

I'm thinking of creating a PR for the following:

```
# Usage: 
# node-definition create [-f|--force] [-v|--verbose] <version>
# node-definition create [-f|--force] [-v|--verbose] <version>,<os>,<arch>,<method>
#
# Create a definition file using default
$ nodenv definition create 0.12.1

# Create a definition file with the a specific version, os, arch, and method.
$ nodenv definition create 0.12.1,osx,x64,copy
```

The plugin will download the correct SHASUMS256.txt file from either nodejs.org or iojs.org and grep the checksum using the provided version, os and arch.

The above example would generate the following:

```
install_package "node-v0.12.1-darwin-x64" "https://nodejs.org/dist/v0.12.1/node-v0.12.1-darwin-x64.tar.gz#1724e75c32ac58452e0ca3eae25120ab67e3b1383da7c10278b33c0f2d3385bf" 0.12.1 copy
```

I have most of the functionality for this working, base on several scripts that I have created for a previous project. 

Also, might be best after aligning/forking rbenv (#13) so as to get the upstream fixes as well.

**Comment by jasonkarns** [comment]
@peterkc How do you envision this working from within the context of nodenv? If the scraper is replaced, would this plugin be used by maintainers to generate definitions files? Be used on-demand by node-build just in time for installing a node?

**Comment by peterkc** [comment]
I'm thinking it should be on demand. If the definition is not there, the user will be prompted to create one and asked if it should be a binary or source install and proceed accordingly.


- Peter C

**Comment by jasonkarns** [comment]
Now that we have iojs definitions in node-build, i'm closing this issue.

@peterkc let's move any further discussion related to installing binaries to https://github.com/OiNutter/node-build/issues/11
