### ISSUE TITLE
Update wiki with nodenv-npm-migrate plugin

### ISSUE THREAD

**Issue by jawshooah** [OiNutter/nodenv#17]
Branch with changes is here: https://github.com/jawshooah/nodenv-wiki/tree/nodenv-npm-migrate

I also sorted the plugins alphabetically.

**Comment by jasonkarns** [comment]
Lgtm

**Comment by jawshooah** [comment]
Ah, didn't notice I had edit permissions for the wiki. I'll add it myself, then :smile:

**Comment by jasonkarns** [comment]
Yeah I think the wiki edits are public
