### ISSUE TITLE
Are you interested in taking over my nodeenv-installer?

### ISSUE THREAD

**Issue by fgimian** [OiNutter/nodenv#18]
Hello there, hope you're well :smile: 

Some time ago, I created a [nodeenv-installer](https://github.com/fgimian/nodenv-installer) which automatically installs nodeenv (similar to rbenv-installer or pyenv-installer).

Since this is a small bash script, I was wondering if you wanted to take over the project and continue it so that you have an easier install method for nodeenv.

Please let me know your thoughts :smile: 
Fois

**Comment by jasonkarns** [comment]
I don't want to speak for anyone else...

But I'm curious, is nodenv-installer significantly different (from a user perspective) than installing via homebrew? I've only ever seen rbenv/nodenv guides show installation through git and homebrew.

**Comment by fgimian** [comment]
I haven't tried through brew actually, does it install node-build as well?  If so, then I would probably use brew on OS X instead of the installer.

The installer honestly is super simple and just allows anyone to install nodeenv on any system:

The guts of it is:

```bash
NODENV_ROOT="${HOME}/.nodenv"
git clone https://github.com/OiNutter/nodenv.git "${NODENV_ROOT}"
git clone https://github.com/OiNutter/node-build.git "${NODENV_ROOT}/plugins/node-build"
```

:smile: 

Cheers
Fotis

**Comment by jasonkarns** [comment]
> does it install node-build as well

Yeah, there is a homebrew tap specifically for nodenv, node-build, and a bunch of the nodenv plugins: https://github.com/jawshooah/homebrew-nodenv

**Comment by fgimian** [comment]
If that's the case, then yeah, I'd suggest using your solution for OS X mate :smile: 

My nodeenv-installer is the equivalent to [rbenv-installer](https://github.com/fesplugas/rbenv-installer) and [pyenv-installer](https://github.com/yyuu/pyenv-installer).

**Comment by jasonkarns** [comment]
I'm going to leave this open in case @OiNutter or the other maintainers have a different opinion.

**Comment by jasonkarns** [comment]
closing in favor of the homebrew tap
