### ISSUE TITLE
"unable to install NodeJS `0.12' from binary, download not available"

### ISSUE THREAD

**Issue by benklebe** [OiNutter/nodenv#20]
nodenv install seems broken when running from boxen. When running nodenv install --list, I get:

```
nodenv: unable to install NodeJS `--list' from binary, download not available
```

I get the same message when trying to nodenv install 0.12.7 or any other version not currently installed. Perhaps I'm just being an idiot but I've been hacking on this for an hour and need to move on to other things. I appreciate any help I can get.

**Comment by jawshooah** [comment]
[Wrong nodenv](https://github.com/wfarr/nodenv).

**Comment by benklebe** [comment]
I'm running the latest version of boxen, it's supposed to use this version of nodenv.

**Comment by jawshooah** [comment]
Something's gone wrong with boxen, then, because that error message is from [the other one](https://github.com/wfarr/nodenv/blob/a49ec629f997033ce8243785588bba274b3aa6a9/libexec/nodenv-install#L115).

**Comment by benklebe** [comment]
I deleted all of the folders related to nodenv and node-build, the ran boxen. Boxen installed the right version and now it's good to go. Thanks for the help!
