### ISSUE TITLE
Accept version specifier with `v` prefix

### ISSUE THREAD

**Issue by jasonkarns** [OiNutter/nodenv#22]
wfarr's version of nodenv accepts the `v` prefix. What do other version managers accept? Do they accept the version specifier both with and without the v prefix? Require it? Require no prefix?

How should we handle this? One possibility is to use https://github.com/jasonkarns/nodenv-aliases to create prefixed symlinks.

Alternatively, we could read in the version specifier and attempt an exact match. If that fails, attempt a match with/without the prefix as a fallback. (This would marginally increase lookup times, but only in the case that the user is using a version spec that doesn't match their builds precisely.)

**Comment by technicalpickles** [comment]
I'm really less concerned about this than the issue I reported in https://github.com/OiNutter/nodenv/issues/21 where it just hangs if the node version doesn't exist, regardless of it's truely missing, incorrectly specified, or has an unsupported 'v' in it.

**Comment by joneslee85** [comment]
IHMO with and without prefix should are all supported.  I could take care this feature if the @OiNutter gives the greenlight

**Comment by technicalpickles** [comment]
Excellent, thanks!
