### ISSUE TITLE
Expose version-name and version-origin hooks

### ISSUE THREAD

**Issue by jasonkarns** [OiNutter/nodenv#29]
Duplicate of https://github.com/sstephenson/rbenv/pull/739 for nodenv discussion

I originally opened that PR against rbenv some time ago to add hooks for version-name and version-origin. Those hooks would expose a point at which plugins could alter the selected ruby version (and its associated origin). The primary use-case for these hooks is for plugins such as [rbenv-bundler-ruby-version](https://github.com/aripollak/rbenv-bundler-ruby-version) (wherein the ruby version is selected from a Gemfile instead of .ruby-version). There seems to be some movement on this PR and it appears likely it be included in rbenv 1.0.

Recently, a new nodenv plugin landed [nodenv-package-json-engine](https://github.com/hurrymaplelad/nodenv-package-json-engine) that does precisely the same thing as rbenv-bundler-ruby-version. (Pulling a node version from package.json engines, instead of .node-version.) The implementations of these plugins are error-prone due to the limitations of rbenv/nodenv. Introducing the hooks I propose will allow the plugins to be implemented in a more robust fashion. (consistent bin resolution with nodenv core; consistency between nodenv-version and nodenv-which)

However, there are other blockers to rbenv 1.0 that I'd rather not wait for. I'd like to see this PR merged into nodenv so that [nodenv-package-json-engine](https://github.com/hurrymaplelad/nodenv-package-json-engine) can take advantage of the new hooks. (As it stands now, the lack of these hooks is significantly hindering iojs support.)

Are there any concerns about merging this PR to nodenv?

Copy of the original PR description follows:

> - version-name hook
  It is invoked *after* the traditional `RBENV_VERSION` lookup. Which means hook scripts can interrogate `$RBENV_VERSION_FILE` and/or `$RBENV_VERSION` (or use the executables).

>  The hooks are then run, giving plugins a chance to alter `RBENV_VERSION`. Once the hooks have run, we now have (in `$RBENV_VERSION`) the actual version we want to use (or it's empty which defaults to `system` per normal). Lastly, the same logic remains for checking if the version exists, or trimming the `ruby-` prefix.
- version-origin hook

>  It is invoked *before* the traditional `rbenv-version-file` lookup. Because `version-origin` is usually run immediately after `version-name`, then any plugin hooks that alter `version-name` would have done so. Thus, running `version-origin` prior to printing the origin gives those plugins a chance to alter the `version-origin` to match. If any of the hooks set `$RBENV_VERSION_ORIGIN`, then it is used as the return value. Otherwise, the existing logic continues to return "environment variable" or "filename" as appropriate.

> With both of these hooks in place, we have a clean seam by which plugins can inject their own ruby-version-setting logic. Until now, the only mechanism to available to alter the chosen ruby version was in the `which` hook. Using the `which` hook is error prone, however, since the hooks must build up the full
`RBENV_COMMAND_PATH` themselves. Further, with the `which` hook, commands like `rbenv version` will report a different ruby than they one that will actually be executed. And functions like `__rbenv_ps1` report the wrong ruby version.

> Using these new hooks, plugins can safely manipulate the version of ruby chosen, while still leaving the executable-path-lookup to rbenv.

**Comment by hurrymaplelad** [comment]
+1 This would make `nodenv-package-json-engine` much cleaner.  Thanks for writing this up @jasonkarns
