### ISSUE TITLE
Missing environment variables (PS1, ...)

### ISSUE THREAD

**Issue by AaronO** [OiNutter/nodenv#3]
I'm using `nodenv` with `boxen`. I have a `node` application that inspects the `PS1` environment variable to see what the current command line prompt is. (It needs to pass this environment variable then to other programs it forks).

However it seems like either `nodenv` or `boxen` are removing this variable. All environment variables of the form `PS*` (where `*` is a digit) are blocked and not accessible through `process.env.PS1`.

Any idea of what may be causing this ?

**Comment by OiNutter** [comment]
@armanm No, it's something that's currently being discussed but I need to do some investigating to see what's required to support precompiled binaries, assuming the library doesn't already. Unfortunately my day job has been crazy busy so my OS stuff is taking a hellish back seat.

**Comment by jasonkarns** [comment]
As this seems to clearly be an issue with @wfarr's version, can this be closed?
