### ISSUE TITLE
References to https://github.com/sstephenson/nodenv

### ISSUE THREAD

**Issue by technicalpickles** [OiNutter/nodenv#30]
I found one in nodenv 0.4.0 in `nodenv --help`. A [code search](https://github.com/OiNutter/nodenv/search?muted=true&q=sstephenson+-language%3AMarkdown+-language%3AYAML&utf8=✓) shows a couple other places.

**Comment by jasonkarns** [comment]
thanks! (one of the search results results is intentional since we don't have a wiki entry on node-local-exec)
