### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jzaefferer** [OiNutter/nodenv#31]
Looking at https://github.com/OiNutter/nodenv/blob/master/LICENSE I'm missing any mention of the name Sam Stephenson. As the [rbenv LICENSE](https://github.com/sstephenson/rbenv/blob/master/LICENSE) states: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." Since this project is a substantial clone of rbenv, not including the original copyright notice seems like a violation of their license. ~~Besides, it also seems rude to not even mention the original project anywhere in the readme.~~

**Comment by OiNutter** [comment]
Not sure of the legal detail of how we'd do that, as I'm not sure if we'd still need a separate license for this project as well as referencing the original rbenv license but I'm happy to do whatever is the correct way to do this appropriately. I think the way I understood it was that the actual license details must remain the same, i.e I couldn't change it to prevent people copying nodenv, that is probably a flawed understanding though.

However we absolutely DO credit rbenv in the README, in the conveniently named Credits section at the end of the README and as far as I'm concerned we've always been totally transparent about the fact this is a clone of rbenv that is adapted for node. If you think we should be making more mention of that I'm happy to review suggestions but I would be wary of confusing people who just want to know how to use nodenv and aren't too worried about it's history.

**Comment by jzaefferer** [comment]
Sorry, I missed the Credits section at the end. Nevermind that part.

As for the license, since you didn't keep the copyright notice intact, something needs to change. I suggest just adding Sam's name on the first line, next to yours.

**Comment by jzaefferer** [comment]
For the readme, you could add the Credits header to the ToC.

**Comment by jzaefferer** [comment]
:+1:

**Comment by OiNutter** [comment]
Have also updated the node-build LICENSE. No ToC on that README though as it's a lot shorter so left that alone.

**Comment by jzaefferer** [comment]
One more thing: The dates on the copyright notice are outdated. Afaik you're better off removing the year, like https://github.com/jquery/jquery/commit/66e1b6b8d49812239b5712d65922ff94c60f7b02
