### ISSUE TITLE
How do I add new versions of node that are not listed here?

### ISSUE THREAD

**Issue by fraserxu** [OiNutter/nodenv#38]
Hi @OiNutter , I've noticed that a newer LTS version(v4.2.4) of node has been released, but it's not available yet from `nodenv install -l`.

I can't find any doc anywhere that could show me how to add new versions, either in the code. Can you please tell me how to add new versions? Thanks!

**Comment by novemberborn** [comment]
@fraserxu [node-build](https://github.com/OiNutter/node-build#readme) takes care of the installs. Its readme mentions the [node-build-update-defs](https://github.com/jasonkarns/node-build-update-defs) plugin, which is what I use.

Takes a bit of digging through the readmes to find it though! :smile:

**Comment by jasonkarns** [comment]
4.2.4 was added to node-build [19 days ago](https://github.com/OiNutter/node-build/commit/bc9f471086fa9744f972f0e20a76a8eb5719a090)

If you're local install of node-build doesn't have 4.2.4, then your version of node-build is out of date and you need to update it. The method for updating obviously depends on [how you installed it](https://github.com/OiNutter/nodenv#installation)

If you installed node-build as a plugin to nodenv (via git-clone), then you can just git-pull to get latest. And I recommend using the [nodenv-update plugin](https://github.com/charlesbjohnson/nodenv-update) to keep nodenv plugins up to date.

If you installed node-build via homebrew (either directly, or as part of nodenv), then you'll need to update using `brew upgrade nodenv` or `brew upgrade node-build`.

The plugin that @novemberborn mentioned above ([node-build-update-defs](https://github.com/jasonkarns/node-build-update-defs)) is a way to scrape build definitions from nodejs.org *before* they are included in node-build itself (or without updating node-build). In this case, 4.2.4 is already in latest node-build, so just updating node-build will give you the newer build definitions.

**Comment by fraserxu** [comment]
@novemberborn @jasonkarns Thanks!
