### ISSUE TITLE
Homebrew installation

### ISSUE THREAD

**Issue by maxnordlund** [OiNutter/nodenv#5]
The current [formula][1] for nodenv in homebrew points to [wfarrs variant][2], not this. I've posted an issue (Homebrew/homebrew/issues/28955) about which one should be in homebrew but thought I should let you know as well.

[1]: /Homebrew/homebrew/blob/master/Library/Formula/nodenv.rb
[2]: /wfarr/nodenv

**Comment by fajpunk** [comment]
Here's a PR to at least clarify this in the README: https://github.com/OiNutter/nodenv/pull/11

**Comment by jawshooah** [comment]
@OiNutter I've created a [homebrew-nodenv](https://github.com/jawshooah/homebrew-nodenv) tap for your version of nodenv and your [node-build](https://github.com/OiNutter/node-build) and [nodenv-vars](https://github.com/OiNutter/nodenv-vars) plugins. To install, just `brew tap jawshooah/nodenv && brew install jawshooah/nodenv/nodenv`.

**Comment by jasonkarns** [comment]
+1 to @jawshooah's tap

**Comment by jasonkarns** [comment]
Closing this as we have @jawshooah's tap which was added to the readme in #12.

More discussion on getting into homebrew main as the primary `nodenv` formula can carry on at https://github.com/Homebrew/homebrew/pull/32193
